name: Deployment

on:
  push:
    branches:
      - main
      
jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: run
        run: echo dev 1
        
  prod:
    needs: dev
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: run
        run: echo prod 1
        
     